apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
  workspaces:
    - name: shared-data
    - name: maven-settings
    - name: maven-local-m2
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-quarkus
      runAfter: ["fetch-source"]
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: shared-data
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-m2
      params:
        - name: GOALS
          value:
            - package
            - -Dnative
    - name: build-oci-push
      runAfter: ["build-quarkus"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.native