apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push-run
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: maven-settings
      emptyDir: {}
    - name: maven-local-m2
      persistentVolumeClaim:
        claimName: maven-local-m2-pvc
    - name: docker-config
      secret:
        secretName: docker-config
  params:
    - name: repo-url
      value: https://github.com/ipt-jbu/testapp.git
    - name: image-reference
      value: harbor.vm.japabu.ch/library/testapp:latest