apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: docker-registry
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: docker-registry
    repoURL: https://helm.twun.io
    targetRevision: 2.2.3
    helm:
      valuesObject:
        ingress:
          enabled: true
          hosts:
            - reg.{{ .Values.host }}
