apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: docker-registry
  project: default
  source:
    repoURL: https://helm.twun.io
    chart: docker-registry
    targetRevision: 2.2.3
    helm:
      valuesObject:
        ingress:
          enabled: true
          hosts:
            - {{ .Values.registry-subdomain }}.{{ .Values.host }}
