apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: quarkus
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: quarkus
      template:
        params:
          - name: quarkus
        resourceTemplates:
          - apiVersion: tekton.dev/v1beta1
            kind: PipelineRun
            metadata:
              generateName: quarkus-
            spec:
              pipelineRef:
                name: quarkus
              workspaces:
                - name: shared-data
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 1Gi
                - name: maven-local-m2
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 3Gi
              params:
                - name: repo-url
                  value: https://github.com/ipt-jbu/testapp.git