apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.cluster.server }}
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.2
    helm:
      valuesObject:
        expose:
          ingress:
            hosts:
              core: {{ .Values.harbor.subdomain }}.{{ .Values.host }}
        core:
          image:
            repository: bitnami/harbor-core
            tag: 2.12.2
        portal:
          image:
            repository: bitnami/harbor-portal
            tag: 2.12.2
