apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.cluster.server }}
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: harbor
    targetRevision: 24.1.8
    helm:
      valuesObject:
        expose:
          ingress:
            hosts:
              core: {{ .Values.harbor.subdomain }}.{{ .Values.host }}
