apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.cluster.server }}
    namespace: harbor
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.2
    helm:
      valuesObject:
        ingress:
          expose:
            ingress:
              hosts:
                core: {{ .Values.harbor.subdomain }}.{{ .Values.host }}
