apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.cluster.server }}
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: harbor
    targetRevision: 24.1.8
    helm:
      valuesObject:
        clusterDomain: {{ .Values.host }}
        externalURL: {{ .Values.harbor.subdomain }}.{{ .Values.host }}
        exposureType: ingress
        ingress:
          core:
            hostname: {{ .Values.harbor.subdomain }}.{{ .Values.host }}
