apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.cluster.server }}
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: harbor
    targetRevision: 24.1.8
    helm:
      valuesObject:
        adminPassword: Harbor12345
        clusterDomain: {{ .Values.host }}
        externalURL: http://{{ .Values.harbor.subdomain }}.{{ .Values.host }}
        exposureType: ingress
        service:
          type: ClusterIP
        ingress:
          core:
            ingressClassName: {{ .Values.ingress.className }}
            hostname: {{ .Values.harbor.subdomain }}.{{ .Values.host }}
            tls: true
            selfSigned: true
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              cert-manager.io/cluster-issuer: lets-encrypt
        core:
          resourcesPreset: nano
        jobservice:
          resourcesPreset: nano
        portal:
          resourcesPreset: nano
        trivy:
          resourcesPreset: nano

