apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    k8s.ngrok.com/modules: ngrok-module-set
    k8s.ngrok.com/domain: "*.{{ .Values.host }}"
spec:
  ingressClassName: ngrok
  rules:
    - host: {{ .Values.argocd.subdomain }}.{{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https