---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ngrok
  namespace: ngrok-operator
spec:
  encryptedData:
    apikey: AgARJok0fqoRLdukia+GcZ3Uva61OEmkOuS+14mkiHF3pMm+zm4Yi5KNqwS0UD9THuJQre1Agi7fYIEc33NVQAVJEn/+sbCW1AF+nmbeXHmjNcy9LbMjs02qpFrc+iu2vn6p0XDPhUQYdlY43RRs6l4cDbij/WuafXZUe5MMiNmY0KU1PnyjvlXl0oSzvkIEVWQqQhmq15X2o33CqD3DWEVmDetHYZAuoXnYHTmLMfdyRaZN5j2Ddr/XXUaCKIZ5owoCA51ULeRETT84wlcS6SkOQe0+Yb1YUSBJl8TtAatApvYgfLNz2FClmAzNpzU8pXm7dmQLwQK/ENEJ3cWSQCL1sl7EFXT7bqoZhchAdpB0XtniCNZNzBa+pCCx8oUVSp0KgSznqbe3vlg5RqgKTZu0ACYfZ3zMCyKcRHEpTd13Hg0eMkJpIjQKJRziNb9Jb5vPEtDpLdyFp8cu/xcJe4s9rdT3Erdy7rt3MJpHrL7PHQX02vuDTWu1GM0+8oziOSLyeIZPOm4P17ToeY3iHEFgOJiilB+NfhokLSWeAQWOuGzuwd4Cjf9wMQLaRLilmljsVXRUtE7NPOl8vCQwzFcL/IPsBNCRuiiAIUH2h7NvGyR+IIrbzGUts3LcUSoXt9f9Z+VYmeMZpBSivdtFfgA9rB77uXlAggP6x2YyRyv6l/VVCUaIpM9z1FHbHyD2FSY4esFDOM/N0KLngJh9hhIfTzhgYgel38Cx2E3/DtNRZG5gLwejke/HY30FQvucFDma
    authtoken: AgBcbPwujQemN1RbHkXxZRyLsCVbXTVgKvkSwIwlVubivNrrQ+vqUxdLs0FLDo9oHwc8ZNg4Bpu7EZwe226OsriKoZbnbfEaLnGV98DzeZBw0pI+VY+rACrNAVOZCOTBBcG/pKjNkxg0qF9ungtOXhtIq2nLBlUCzSZ58UK/9r7VOdhwZtQggQ7/QmXV93iRUCyT4qjE2KXq4mSvzDI7x89q7TEkYY2mqv07KjivpxGAk/naZOM7LeZixa88gVfoslAcErGQS8Lb0XeuvkrBi61+QjARcYSJNtgjt+4W5C8M+F0aUZURFK0iM42YpDJC89t80WdNKfOiU91VUpfGE8EcajBtJst3APLRPgC+rOPnA5tvduTjz2wzd110jZShkSVz/lEFUWyuF2BECGt8FFyQaUsi+IQJ++0kVkc2Hwdn6hivrQtInVecULmIz+or0p102siPGJYwuR+0OE6Q5qirqmPtL3W3rSpTpHILPo6x+zPN2SONCfrWkUSaBtXYsdN9TUaLJkvodibDCTMpL4g1QmIgo5knjLc5X9fySdEfe7xyq4TLgusClZuk2NTpKQpP2MdwveGVmBCdsHZgKm6zDtrbSmF41yI+mIf6zKEEtySLvYuWRpSwnypqaHEQcaAT+1rpdFqE8luMmjnkC1naJWYJzrQfSJhpWzDSGpx2uzGNkZS6lUzZHeHhAlMVrZwj7w4u7ri0so9g5XrP4lKW6T9ABtmEqfQK+Tuw8T3c9L8IRCT1+iw6by6Bbk75j8BU
  template:
    metadata:
      creationTimestamp: null
      name: ngrok
      namespace: ngrok-operator
