apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    server: {{ .Values.cluster.server }}
    namespace: tekton-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: tekton
  source:
    repoURL: https://kubebb.github.io/components
    chart: tekton-operator
    targetRevision: 0.64.0