apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tekton-operator
    server: {{ .Values.spec.destination.server }}
  project: tekton
  source:
    repoURL: https://kubebb.github.io/components
    chart: tekton-operator
    targetRevision: 0.64.0
---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all