apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  description: |
    This pipeline clones a git repo, then builds it and pushes the image.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
  workspaces:
    - name: shared-data
    - name: maven-local-m2
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-and-push
      runAfter: ["fetch-source"]
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: shared-data
        - name: maven-local-repo
          workspace: maven-local-m2
      params:
        - name: GOALS
          value:
            - build
            - -Dquarkus.container-image.push=true
            - -Dquarkus.container-image.registry={{ .Values.registry }}